
trigger: none
pr: none

jobs:
  - job: "macOS"
    pool:
      vmimage: "macos-latest"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          options: '-Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          tasks: 'publishMac'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)

  - job: "Linux"
    pool:
      vmimage: "ubuntu-latest"
    dependsOn: 'macOS'
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          options: '-Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          tasks: 'publishLinux'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)

  - job: "Windows"
    pool:
      vmimage: "windows-latest"
    dependsOn: 'Linux'
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          options: '-Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          tasks: 'publishWindows'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)
