
trigger: none

jobs:
  - job: "macOS"
    pool:
      vmimage: "macos-latest"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'publishMac'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)

  - job: "Linux"
    pool:
      vmimage: "ubuntu-latest"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'publishLinux'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)

  - job: "Windows"
    pool:
      vmimage: "windows-latest"
    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'publishWindows'
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: $(sonatype_user)
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: $(sonatype_password)
          ORG_GRADLE_PROJECT_PGP_SIGNING_KEY: $(secret_key)
