# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios target
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.9.0'
  pod 'shared', :path => '../shared'

end
